### ISSUE TITLE
未定义函数或变量 'derivcent'。

### ISSUE THREAD

**Issue by zhLawliet** [mahdihosseini/1Shot-MaxPol#1]
请教一个问题，之前可以正常跑，隔了几个月跑，发现不行了……求解答
未定义函数或变量 'derivcent'。

出错 deblurring_kernel_estimation (line 39)
    d(1, :) = derivcent(l_deblurring, 2*l_deblurring, 0, 0, false);

**Comment by Redamancy0222** [comment]
Hello, I'm not sure if you need this part of the code now. Download this code package, it contains ‘derivcent’.
[https://github.com/mahdihosseini/MaxPol]
